name: superBAR
main: FaigerSYS\superBAR\superBAR
version: 2.0.0
api: [3.0.0-ALPHA6, 3.0.1]
load: POSTWORLD
author: Zeao
description: "Just good and customizable HUD"
website: "Not showing information due to seld-leak."

commands:
 superbar:
  description: "superBAR command"
  aliases: [sb, supbar, sbar]
  permission: "superbar.cmd"

permissions:
 superbar:
  default: op
  description: "Use all features (commands and other) of superBAR"
 superbar.use:
  default: true
  description: "Use HUD (You can see HUD)"
 superbar.cmd:
  default: true
  description: "Use superBAR commands"
 superbar.help:
  default: true
  description: "Use superBAR help"
 superbar.switch:
  default: false
  description: "Enable/Disable HUD for you"
 superbar.change:
  default: op
  description: "Change settings via command"
 superbar.reload:
  default: op
  description: "Reload settings"
